### ISSUE TITLE
recent releases aren't using recognized semantic version numbers

### ISSUE THREAD

**Issue by c-robinson** [SolarLune/Tetra3d#12]
...and `go mod` is unhappy with them. Currently it believe v0.5.2 is the most recent release because its the most recent one with "acceptable" semantic versioning per https://go.dev/doc/modules/version-numbers

To fix, re-release v0.8 as v0.8.0 or v0.8.1

**Comment by SolarLune** [comment]
Whoops, sorry about this - I've pushed a new tag with the fixes from master as v0.8.1. Thanks for letting me know!
