### ISSUE TITLE
panic: Error: MeshPart.AddTriangles() not given enough vertices to construct complete triangles (i.e. multiples of 3 vertices).

### ISSUE THREAD

**Issue by xackery** [SolarLune/Tetra3d#20]
I'm noticing a trend in this package:

```go
func (part *MeshPart) AddTriangles(verts ...VertexInfo) {

	mesh := part.Mesh

	if part.TriangleEnd > -1 && part.TriangleEnd < mesh.triIndex {
		panic("Error: Cannot add triangles to MeshPart non-contiguously (i.e. partA.AddTriangles(), partB.AddTriangles(), partA.AddTriangles() ).")
	}

	if len(verts) == 0 || len(verts)%3 > 0 {
		panic("Error: MeshPart.AddTriangles() not given enough vertices to construct complete triangles (i.e. multiples of 3 vertices).")
	}
```

Is there any reason sanity checks constitute an entire program failure? why not restructure to..

```go
func (part *MeshPart) AddTriangles(verts ...VertexInfo) error {

	mesh := part.Mesh

	if part.TriangleEnd > -1 && part.TriangleEnd < mesh.triIndex {
		return fmt.Errorf("cannot add triangles to MeshPart non-contiguously (i.e. partA.AddTriangles(), partB.AddTriangles(), partA.AddTriangles() ).")
	}

	if len(verts) == 0 || len(verts)%3 > 0 {
		return fmt.Errorf("not enough vertices are provided to construct complete triangles (i.e. multiples of 3 vertices).")
	}
```

There are 26 uses of panic in this package: https://github.com/SolarLune/Tetra3d/search?q=panic
And most aren't critical failures that require the entire application to exit immediately, most are simply malformed requests that can be reported back to abort current operation

**Comment by SolarLune** [comment]
Hello, thanks for the question!

A lot of those panics are panics in the examples, firstly. However, the other panics are generally where if Tetra3D were to not panic, the program would proceed in an unusable state, either giving a malformed render (where the user might think there's an issue with their mesh, export, code, etc., when it's simply a matter of ordering AddTriangles calls, in this case), or crashing later on down the line (which doesn't seem much better than panicking early on the specific problem). 

Is there a reason why a failed sanity check should not crash the program?

**Comment by xackery** [comment]
Sounds good!
