### ISSUE TITLE
Properties.Get documentation is incorrect

### ISSUE THREAD

**Issue by scw007** [SolarLune/tetra3d#30]
https://github.com/SolarLune/tetra3d/blob/c4f7bb67abc2de882682eb558c2fb0245694e8f0/properties.go#L42

The comment says that `Get` returns `nil`, but it definitely does not. It seems like this is the only way to set a property initially. So either the docs here are wrong, or its intended to set properties a different way?

I would have gone ahead and opened a PR to fix the doc, but I wasn't sure what the intention was.

**Comment by SolarLune** [comment]
Whoops, my bad - you're right on that. I've updated the documentation to be correct.
