### ISSUE TITLE
Lots of noise when displaying triangles

### ISSUE THREAD

**Issue by adamrt** [SolarLune/Tetra3d#7]
Hi I've tried running a few examples with the same results (see the attached).

I'm running Go 1.17 on Debian Stable (5.10.0-10-amd64) via Xorg. The GPU on my Thinkpad is an HD 520.

The video I've attached is of the animations example but the same thing happens on other examples. I've tried on the latest master branch and also checked out the v0.4.2 tag with the same results. 

I know there isn't much you can do remotely for such a weird issue but figured I would still notify you. I'm a go developer myself and have built toy renderers before, but I'm kinda at a loss for how to debug this. If there is something I can do to help, let me know.

Install steps were just `checkout`, `go mod tidy`, `go run ./examples/animation/main.go`.

https://user-images.githubusercontent.com/58468/149854580-e1c5f4a9-4fdc-4797-9eee-9db5260899b3.mp4

**Comment by SolarLune** [comment]
Yo!

Thanks a lot for trying out Tetra! I believe this has to do with the Kage shaders I'm using to render and composite depth; I believe I'm getting similarly messed up results on my cruddy laptop (which is an Acer Switch V 10 and so would have an HD 330 graphics unit). Upside is FPS seems good, which is great, haha.

Can you try turning off depth rendering by setting `Camera.RenderDepth` to false, and see if you still have the same results?

**Comment by adamrt** [comment]
Hey thanks, yes that was it! The original video made it seem like the cube/rectable was textured, but as you can see its black now. That might be normal, but figured I'd throw in a screenshot.
![Screenshot from 2022-01-18 09-28-12](https://user-images.githubusercontent.com/58468/149967235-c4b251b8-b407-4e25-8f8d-952ccaca4b50.png)

Thanks again, I'm gonna dive in further now

**Comment by SolarLune** [comment]
No problem - I'd actually like to reopen this because it's an issue I've seen as well on my computer, and that I have yet to resolve. It seems like it might be tied to using if statements in the Kage shaders, but I'm not 100% on that yet.

And nah, the mesh turning black is not correct, it should be textured, as you can partially see in your video.

**Comment by SolarLune** [comment]
OK, so thanks to your direction in your PR, this should be resolved by commit 0d4d98d81e2c4edc17159e631ecd4d002b23b240! Please pull master and let me know if it worked.

**Comment by adamrt** [comment]
Totally! I tried every example and they all work great. For some reason the block bending over in the animation example made me crack up. Nice work and thanks for being so quick with the fix!

**Comment by SolarLune** [comment]
Haha, I'm glad it works and resolves this issue! 

No problem - thanks for trying out Tetra3D, again~
